#=============================== dev ===========================================
spring:
  datasource:
    url: jdbc:mysql://mysql.sqlpub.com:3306/weindependent?serverTimezone=Asia/Shanghai&characterEncoding=utf8&rewriteBatchedStatements=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: wi_user
    password: P1q7SrJqSRwH87Dn
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
#    hibernate:
#      ddl-auto: create
    show-sql: true
#session:
      ##    store-type: redis
      ##  redis:
      ##    host: 127.0.0.1
    ##    password:
    ##    port: 6379
