name: Deploy to Oracle VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}        # Oracle VM IP
          username: ${{ secrets.SSH_USER }}    # Usually ubuntu
          key: ${{ secrets.SSH_KEY }}          # SSH private key for VM
          command_timeout: 30m
          script: |
            set -e
            APP_DIR="$HOME/We-In-Dependent-Backend"
            REPO="https://github.com/we-independent/We-In-Dependent-Backend.git"

            echo "[+] Ensure Git is ready"

            if [ ! -d "$APP_DIR" ]; then
              echo "[+] Directory does not exist. Cloning fresh repository..."
              git clone $REPO $APP_DIR
            else
              echo "[+] Pulling latest changes..."
              git -C $APP_DIR fetch origin
              git -C $APP_DIR reset --hard origin/main
            fi

            echo "[+] Running deployment script"
            chmod +x $APP_DIR/.github/workflows/deploy.sh
            $APP_DIR/.github/workflows/deploy.sh
