name: Deploy to Oracle VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 30m
          script: |
            set -e
            APP_DIR="~/We-In-Dependent-Backend"
            REPO="git@github.com:we-independent/We-In-Dependent-Backend.git"

            echo "[+] Adding GitHub to known hosts"
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts 2>/dev/null

            if [ ! -d "$APP_DIR" ]; then
              echo "[+] Directory does not exist. Cloning fresh repository..."
              git clone $REPO $APP_DIR
            else
              echo "[+] Pulling latest changes..."
              if ! git -C $APP_DIR pull origin main; then
                echo "[!] Pull failed. Removing and recloning..."
                rm -rf $APP_DIR
                git clone $REPO $APP_DIR
              fi
            fi

            echo "[+] Running deployment script"
            chmod +x $APP_DIR/deploy.sh
            $APP_DIR/deploy.sh
