name: Deploy to Oracle VM

on:
  push:
    branches:
      - main  # Trigger when pushing to main branch
  workflow_dispatch: # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}      # Your Oracle VM IP
          username: ${{ secrets.SSH_USER }}  # Usually ubuntu
          key: ${{ secrets.SSH_KEY }}        # Private key from Oracle VM
          command_timeout: 30m               # Increase timeout to 30 minutes
          script: |
            set -e

            APP_DIR="/We-In-Dependent-Backend"
            REPO="git@github.com:we-independent/We-In-Dependent-Backend.git"

            # Clone or update repo
            if [ ! -d "$APP_DIR/.git" ]; then
              echo "[+] Cloning repository..."
              rm -rf "$APP_DIR"
              git clone $REPO $APP_DIR
            else
              echo "[+] Pulling latest code..."
              git -C $APP_DIR reset --hard
              git -C $APP_DIR pull origin main || {
                echo "[!] Pull failed, recloning..."
                rm -rf "$APP_DIR"
                git clone $REPO $APP_DIR
              }
            fi

            echo "[+] Running deployment script"
            cd $APP_DIR/.github/workflows
            chmod +x deploy.sh
            ./deploy.sh
